import { useEffect, useMemo, useState } from 'react';
import { localKnowledgeDocuments, subscribeLocalKnowledge } from '../../runtime/local-knowledge-ledger';
import { providerDiagnosticEntries, subscribeProviderDiagnostics } from '../../runtime/provider-diagnostics';
import { createRealProgressStages } from './real-progress-projection';

const REAL_PROGRESS_STYLE = `.real-progress-panel{display:grid;gap:15px;padding:20px}.real-progress-panel header{display:grid;gap:5px}.real-progress-panel header span{color:var(--accent-strong);font-size:9px;font-weight:800;letter-spacing:.1em}.real-progress-panel h2{margin:0;color:var(--text-strong);font-size:18px}.real-progress-panel p{margin:0;color:var(--muted-strong);font-size:12px;line-height:1.55}.real-progress-panel ol{display:grid;gap:8px;margin:0;padding:0;list-style:none}.real-progress-stage{display:grid;grid-template-columns:10px minmax(0,1fr) auto;gap:10px;align-items:start;padding:12px;border:1px solid var(--border);border-radius:14px;background:var(--panel-subtle)}.real-progress-stage i{width:8px;height:8px;margin-top:5px;border-radius:50%;background:var(--muted)}.real-progress-stage.complete i{background:var(--success)}.real-progress-stage.active i{background:var(--accent)}.real-progress-stage.attention i{background:var(--warning)}.real-progress-stage strong{color:var(--text-strong);font-size:12px}.real-progress-stage em{padding:3px 6px;color:var(--muted);font-size:9px;font-style:normal;border-radius:999px;background:var(--panel-muted);white-space:nowrap}.real-progress-panel footer{padding-top:11px;color:var(--muted);font-size:10px;line-height:1.5;border-top:1px solid var(--border)}@media(max-width:520px){.real-progress-panel{padding:15px}.real-progress-stage{grid-template-columns:10px minmax(0,1fr)}.real-progress-stage em{grid-column:2}}`;

export function RealProgressPanel({ chatError, connectionCount, messageCount, pendingProviderId, streaming }: Readonly<{ chatError?: string; connectionCount: number; messageCount: number; pendingProviderId?: string; streaming: boolean }>) {
  const [, refresh] = useState(0);
  useEffect(() => { const update = (): void => refresh((value) => value + 1); const unlistenProvider = subscribeProviderDiagnostics(update); const unlistenKnowledge = subscribeLocalKnowledge(update); return () => { unlistenProvider(); unlistenKnowledge(); }; }, []);
  const stages = useMemo(() => createRealProgressStages({ connectionCount, pendingProviderId, diagnostics: providerDiagnosticEntries(), knowledge: localKnowledgeDocuments(), streaming, chatError, messageCount }), [chatError, connectionCount, messageCount, pendingProviderId, streaming]);
  return <section aria-live="polite" className="real-progress-panel"><style>{REAL_PROGRESS_STYLE}</style><header><span>LOCAL, EVENT-DRIVEN STATUS</span><h2>真实阶段状态</h2><p>只显示已有本地回执与当前状态；打开此面板不会连接 Provider、上传资料、启动检索或推进任何步骤。</p></header><ol>{stages.map((stage) => <li className={`real-progress-stage ${stage.tone}`} key={stage.id}><i aria-hidden="true" /><div><strong>{stage.label}</strong><p>{stage.detail}</p></div><em>{stage.tone === 'complete' ? '已确认' : stage.tone === 'active' ? '进行中' : stage.tone === 'attention' ? '需关注' : '等待操作'}</em></li>)}</ol><footer>阶段仅由已保存的原生连接诊断、显式本地知识库索引和当前会话状态驱动；不使用自动倒计时。</footer></section>;
}
