import { useEffect, useState } from 'react';
import novaIcon from '../../assets/nova-icon.png';

const splashCss = `.nova-startup-splash{position:fixed;z-index:2147483647;inset:0;display:grid;place-items:center;overflow:hidden;background:radial-gradient(circle at 50% 46%,#204cbb 0,#101c52 28%,#07091a 70%,#03040a 100%);color:#fff;isolation:isolate;animation:nova-splash-exit .22s 1.02s cubic-bezier(.23,1,.32,1) both}.nova-startup-splash:before{content:'';position:absolute;inset:-25%;z-index:-1;opacity:.68;background:radial-gradient(circle at 24% 21%,#3f8cff70,transparent 27%),radial-gradient(circle at 76% 74%,#934cff64,transparent 31%)}.nova-splash-mark{position:relative;display:grid;place-items:center;width:168px;height:168px}.nova-splash-orbit{position:absolute;inset:5px;border:13px solid transparent;border-radius:50%;filter:drop-shadow(0 0 14px #73b3ff70)}.nova-splash-orbit--a{border-top-color:#eef6ff;border-right-color:#d4e7ff;transform:rotate(-23deg);animation:nova-splash-orbit-a 1.04s cubic-bezier(.32,.72,.24,1) both}.nova-splash-orbit--b{inset:17px;border-width:10px;border-bottom-color:#d5baff;border-left-color:#f1eaff;transform:rotate(37deg);animation:nova-splash-orbit-b 1.04s cubic-bezier(.32,.72,.24,1) both}.nova-splash-core{position:relative;z-index:1;width:74px;height:74px;border-radius:50%;box-shadow:0 0 0 9px #fff1,0 0 34px #7db6ffb3;animation:nova-splash-breathe .82s ease-in-out infinite alternate}.nova-splash-core img{display:block;width:100%;height:100%;border-radius:inherit;object-fit:cover}.nova-splash-copy{margin-top:25px;text-align:center}.nova-splash-copy strong{display:block;font:700 19px var(--font-ui);letter-spacing:.22em;text-indent:.22em}.nova-splash-copy span{display:block;margin-top:7px;color:#c7d9ff;font:600 9px var(--font-ui);letter-spacing:.16em}.nova-splash-skip{position:absolute;right:18px;bottom:16px;padding:7px 10px;color:#cbdcff;font:600 10px var(--font-ui);border:1px solid #b9d3ff3d;border-radius:999px;background:#ffffff0d}.nova-splash-skip:focus-visible{outline:2px solid #fff;outline-offset:3px}@keyframes nova-splash-orbit-a{from{opacity:0;transform:rotate(-130deg) scale(.82)}to{opacity:1;transform:rotate(170deg) scale(1)}}@keyframes nova-splash-orbit-b{from{opacity:0;transform:rotate(140deg) scale(.72)}to{opacity:1;transform:rotate(-160deg) scale(1)}}@keyframes nova-splash-breathe{from{transform:scale(.92);box-shadow:0 0 0 7px #fff1,0 0 22px #7db6ff75}to{transform:scale(1.08);box-shadow:0 0 0 14px #fff1,0 0 42px #af90ffcf}}@keyframes nova-splash-exit{to{opacity:0;transform:scale(1.02);pointer-events:none}}@media(prefers-reduced-motion:reduce){.nova-startup-splash{animation:none}.nova-splash-orbit,.nova-splash-core{animation:none}}`;

/** 仅负责最初可见帧的品牌过渡；不等待 Provider、会话账本或懒加载面板。 */
export function StartupSplash() {
  const [visible, setVisible] = useState(true);
  useEffect(() => {
    const reducedMotion = window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
    const timer = window.setTimeout(() => setVisible(false), reducedMotion ? 90 : 1250);
    return () => window.clearTimeout(timer);
  }, []);
  if (!visible) return null;
  return <section aria-label="NOVA 正在启动" className="nova-startup-splash" role="status"><style>{splashCss}</style><div><div className="nova-splash-mark" aria-hidden="true"><i className="nova-splash-orbit nova-splash-orbit--a" /><i className="nova-splash-orbit nova-splash-orbit--b" /><span className="nova-splash-core"><img alt="" src={novaIcon} /></span></div><div className="nova-splash-copy"><strong>NOVA</strong><span>DIRECT AI WORKSPACE</span></div></div><button className="nova-splash-skip" onClick={() => setVisible(false)} type="button">跳过</button></section>;
}
