[CmdletBinding()]
param(
  [ValidateSet('amd64')]
  [string]$Architecture = 'amd64',
  [switch]$Force
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$searxngRoot = Join-Path $projectRoot 'third_party\searxng-windows'
$runtimeRoot = Join-Path $projectRoot 'apps\desktop-shell\src-tauri\resources\research\python-runtime'
$pythonVersion = '3.13.13'
$pythonArchiveName = "python-$pythonVersion-embed-$Architecture.zip"
$pythonUrl = "https://www.python.org/ftp/python/$pythonVersion/$pythonArchiveName"
$bootstrapUrl = 'https://bootstrap.pypa.io/get-pip.py'

if (-not (Test-Path (Join-Path $searxngRoot 'LICENSE'))) {
  throw "Pinned SearXNG source was not found: $searxngRoot"
}

if ((Test-Path (Join-Path $runtimeRoot 'python.exe')) -and -not $Force) {
  Write-Host "SearXNG Python runtime already exists: $runtimeRoot"
  exit 0
}

if (Test-Path $runtimeRoot) { Remove-Item -Force -Recurse $runtimeRoot }
New-Item -ItemType Directory -Force -Path $runtimeRoot | Out-Null
$downloadDirectory = Join-Path $runtimeRoot '.downloads'
New-Item -ItemType Directory -Force -Path $downloadDirectory | Out-Null
$pythonArchive = Join-Path $downloadDirectory $pythonArchiveName
$getPip = Join-Path $downloadDirectory 'get-pip.py'

Write-Host "Downloading pinned CPython embeddable runtime: $pythonUrl"
Invoke-WebRequest -UseBasicParsing -Uri $pythonUrl -OutFile $pythonArchive
Expand-Archive -Force -Path $pythonArchive -DestinationPath $runtimeRoot

$pth = Get-ChildItem -Path $runtimeRoot -Filter 'python*._pth' | Select-Object -First 1
if (-not $pth) { throw 'CPython embeddable _pth configuration file was not found.' }
$pthLines = @(Get-Content -Path $pth.FullName | ForEach-Object { if ($_ -eq '#import site') { 'import site' } else { $_ } })
if (-not ($pthLines -contains 'Lib/site-packages')) { $pthLines = @('Lib/site-packages') + $pthLines }
[System.IO.File]::WriteAllLines($pth.FullName, [string[]]$pthLines, [System.Text.Encoding]::ASCII)

$python = Join-Path $runtimeRoot 'python.exe'
Write-Host "Downloading pip bootstrap: $bootstrapUrl"
Invoke-WebRequest -UseBasicParsing -Uri $bootstrapUrl -OutFile $getPip
& $python $getPip --no-warn-script-location

$coreRequirements = Join-Path $searxngRoot 'requirements.txt'
Write-Host 'Installing pinned SearXNG core dependencies from Windows wheels only...'
& $python -m pip install --disable-pip-version-check --no-cache-dir --only-binary=:all: -r $coreRequirements
& $python -m pip install --disable-pip-version-check --no-cache-dir --only-binary=:all: 'tzdata==2026.3'
$searxPackage = Join-Path $searxngRoot 'searx'
$sitePackages = Join-Path $runtimeRoot 'Lib\site-packages'
if (-not (Test-Path $searxPackage)) { throw "Pinned SearXNG Python package was not found: $searxPackage" }
Copy-Item -Force -Recurse $searxPackage (Join-Path $sitePackages 'searx')
$pwdCompatibility = @'
"""Windows compatibility shim for SearXNG's optional Valkey error logging.

This file is generated by NOVA outside vendored upstream source. SearXNG
imports pwd although the standard module does not exist on Windows. The shim is
only used if an optional Valkey connection error must be logged.
"""
import os
from collections import namedtuple

pwd_struct = namedtuple("pwd_struct", "pw_name pw_passwd pw_uid pw_gid pw_gecos pw_dir pw_shell")

def getpwuid(uid):
    return pwd_struct(os.environ.get("USERNAME", "NOVA"), "x", uid, 0, "", "", "")
'@
Set-Content -NoNewline -Encoding ascii -Path (Join-Path $sitePackages 'pwd.py') -Value $pwdCompatibility

$manifest = [ordered]@{
  schemaVersion = 1
  pythonVersion = $pythonVersion
  architecture = $Architecture
  pythonUrl = $pythonUrl
  pythonSha256 = (Get-FileHash -Algorithm SHA256 $pythonArchive).Hash
  searxngCommit = '9fea41204fdfa7a5cfa15b0ebd12904c520478ce'
  searxngLicense = 'AGPL-3.0'
  localCompatibilityShims = @('pwd.py: Windows-only compatibility shim outside vendored SearXNG source')
  preparedAtUtc = [DateTime]::UtcNow.ToString('o')
  packages = @(& $python -m pip freeze)
}
$manifest | ConvertTo-Json -Depth 4 | Set-Content -Encoding utf8 (Join-Path $runtimeRoot 'runtime-manifest.json')
Copy-Item -Force (Join-Path $searxngRoot 'LICENSE') (Join-Path $runtimeRoot 'SEARXNG-AGPL-3.0.txt')
Remove-Item -Force -Recurse $downloadDirectory
Write-Host "Packaged SearXNG Python runtime prepared: $runtimeRoot"
